In [2]:
import numpy as np
import pandas as pd

neg = pd.read_csv('~/Downloads/negative_articles.csv')
pos = pd.read_csv('~/Downloads/positive_articles.csv')

In [3]:
neg.head()

,article_pk,domain_pk,domain_name,article_url,label,article_headline,article_text
0,42301915,14,independent.co.uk,https://www.independent.co.uk/news/uk/home-new...,0,East Kent maternity scandal: Inquiry begins af...,An investigation into East Kent Hospitals’ mat...
1,24447761,8,cnbc.com,https://www.cnbc.com/2020/03/28/coronavirus-li...,0,"NY Gov balks at federal quarantine talk, CDC w...",The coverage on this live blog has ended — but...
2,34129035,14,independent.co.uk,https://www.independent.co.uk//news/uk/home-ne...,0,Scammers carrying out sextortion cybercrimes d...,Scammers are carrying out sextortion cybercrim...
3,1397777,6,cbsnews.com,https://www.cbsnews.com/news/cbs-this-morning-...,0,"Listen to the ""CBS This Morning"" podcast","The ""CBS This Morning Podcast"" offers listener..."
4,14548788,1594,businessinsider.com,http://www.businessinsider.com/?IR=T,0,NaN,A vertical stack of three evenly spaced horizo...